# This config should be placed in following path:
#   ~/.local/share/io.parity.ethereum/config.toml

[parity]
# Ropsten Test Network
chain = "ropsten"
# Parity continously syncs the chain
mode = "active"
# Specify the number of blocks between each auto-update check.
auto_update_check_frequency = 10
# You will be identified as 'bitwyre-eth-node' amongst other nodes..
identity = "bitwyre-eth-node"

[network]
# Parity will try to maintain connection to at least 5 peers.
min_peers = 5

[rpc]
# Allows Cross-Origin Requests from domain '*'.
cors = ["*"]
# Allow connections only using specified addresses.
hosts = ["*"]
# Only selected APIs will be exposed over this interface.
apis = [
    "web3", "eth", "pubsub", "net", "parity", "private", "parity_pubsub", "traces", "rpc", "shh", "shh_pubsub",
    "parity_transactions_pool", "personal", "parity_accounts", "secretstore"
]
# Threads for handling incoming connections for HTTP JSON-RPC server.
server_threads = 2

[websockets]
# Only selected APIs will be exposed over this interface.
apis = [
    "web3", "eth", "pubsub", "net", "parity", "parity_pubsub", "private", "traces", "rpc", "shh", "shh_pubsub", 
    "parity_transactions_pool", "personal", "parity_accounts", "secretstore"
]

[ipc]
# Only selected APIs will be exposed over this interface.
apis = [
    "web3", "eth", "pubsub", "net", "parity", "parity_pubsub", "parity_accounts", "private", "traces", "rpc", "shh", 
    "shh_pubsub", "parity_transactions_pool", "personal", "secretstore"
]
